import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar, type SidebarItemType } from "@/components/ui/sidebar";
import { ToastProvider } from "@/components/ui/toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigationItems: SidebarItemType[] = [
  { href: '/buttons', label: 'Button' },
  { href: '/button-examples', label: 'Button Examples' },
  { href: '/avatar', label: 'Avatar' },
  { href: '/checkbox', label: 'Checkbox' },
  { href: '/radio', label: 'Radio' },
  { href: '/switch', label: 'Switch' },
  { href: '/progress', label: 'Progress' },
  { href: '/popover', label: 'Popover' },
  { href: '/toast', label: 'Toast' },
  { href: '/toggle', label: 'Toggle' },
  { href: '/select', label: 'Select' },
  { href: '/tabs', label: 'Tabs' },
  { href: '/scroll-area', label: 'Scroll Area' },
  { href: '/tooltip', label: 'Tooltip' },
  { href: '/number-field', label: 'Number Field' },
  { href: '/placeholder', label: 'Placeholder' },
]


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-surface text-primary-fg`}
      >
        <ToastProvider>
          <div className="flex min-h-screen">
            <Sidebar items={navigationItems} />
            <main className="flex-1 overflow-auto">
              {children}
            </main>
          </div>
        </ToastProvider>
      </body>
    </html>
  );
}
